### ISSUE TITLE
Executable file parameters

### ISSUE THREAD

**Issue by AlexeyArtemev** [nedsociety/pysandboxie#10]
Is there a way to determine parameters for an executable file?

i've tried to open SAMP.exe with parameter -n="My_Name":
`sb.execute(["samp.exe -n'My_Name'"], name = my_sandbox)`_(there should be no separator between parameter(-n) and value('My_Name'))_
using this example i got "Unable to locate file" error

**Comment by nedsociety** [comment]
You're trying to execute a file named as `samp.exe -n'My_Name'` without an argument. Refer to the `subprocess.popen` docs.

I'd guess the correct invocation would be `['samp.exe', '-nMy_Name']`.
