### ISSUE TITLE
Poetry add error, because of pywin32 dependency

### ISSUE THREAD

**Issue by nubonics** [nedsociety/pysandboxie#14]
Hi, I was trying to install pysandboxie via a poetry environment, but it was failing due to the requirement of pywin32, and I was wondering if you could update the dependencies?

At the time of writing, pywin32==304 is the latest version, while pysandboxie requires version pywin32==300

```python
(venv) C:\Users\nubonix\PycharmProjects\Overseer\OSG\src\osg>poetry add git+https://github.com/nedsociety/pysandboxie.git 

Updating dependencies
Resolving dependencies...

Because pysandboxie (0.2.0) @ git+https://github.com/nedsociety/pysandboxie.git@HEAD depends on pywin32 (^300)
 and osg depends on pywin32 (^304), pysandboxie is forbidden.
So, because osg depends on pysandboxie (0.2.0) @ git+https://github.com/nedsociety/pysandboxie.git, version solving failed.
```

**Comment by nedsociety** [comment]
[48cf2d8](https://github.com/nedsociety/pysandboxie/commit/48cf2d8daf0169c8fe4fcaa6a38f60b98b445383)
