### ISSUE TITLE
object error

### ISSUE THREAD

**Issue by ABetterCat** [nedsociety/pysandboxie#9]
When i run code followed, the object excutes exe is not sandboxie named "testpy".It is the defaultbox.

`
import sandboxie

sbie = sandboxie.Sandboxie()

settings = sbie.make_sandbox_setting('default')
sbie.create_sandbox('testpy', settings=settings)

proc = sbie.execute(['notepad.exe'], 'testpy')
print(proc.wait())

sbie.execute(['notepad.exe'], 'testpy')
sbie.terminate_sandbox_processes('testpy')
sbie.delete_content('testpy')   
sbie.remove_sandbox('testpy'
`

**Comment by nedsociety** [comment]
![image](https://user-images.githubusercontent.com/11943013/173186943-1428be7b-46ff-4160-bc86-7a0e80f8f3a9.png)

Can't reproduce. What's your Sbie version and pysandboxie commitid?

**Comment by ABetterCat** [comment]
![image](https://user-images.githubusercontent.com/40079947/173187326-8a3b277d-47a8-47d7-86d9-0c3e2f33a00c.png)
![image](https://user-images.githubusercontent.com/40079947/173187336-d80f7c96-72b8-4e1a-bf57-96d15ec1ad41.png)

**Comment by ABetterCat** [comment]
![image](https://user-images.githubusercontent.com/40079947/173187370-2dc94ba1-e1ec-41dc-8c49-cef9a9afb2a9.png)

**Comment by nedsociety** [comment]
Should be working for that version.

If you manually create a box called testpy and then run following (adjust path to your Sandboxie installation), does it spawn in testpy?

`"C:\Program Files\Sandboxie-Plus\Start.exe" /box:testpy /wait notepad.exe`

**Comment by ABetterCat** [comment]
![image](https://user-images.githubusercontent.com/40079947/173187877-852b8b85-9226-45e1-a78a-92a6c5aded2a.png)
It is ok

**Comment by ABetterCat** [comment]
My installed path is "E:\install\Sandboxie".Should I change it?

**Comment by nedsociety** [comment]
The script should work without changing the installation path.

Could you debug into `sbie.execute()` call, break at [this line](https://github.com/nedsociety/pysandboxie/blob/87ec0fa06ca20dfc060d33eee8412ca18fd52fe3/sandboxie/sandboxie.py#L406) and then dump what `invocation_sandboxie` and `cmd` has?

**Comment by ABetterCat** [comment]
sorry.I have run it successfuly.I didn't put param name into it.
